2020-01-15 11:46:58,284 ERROR: Exception on /search [GET] [in /home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/flask/app.py:1890]
Traceback (most recent call last):
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/aman/Projects/Flask/microblog/app/main/routes.py", line 144, in search
    posts, total = Post.search(g.search_form.q.data, page,
  File "/home/aman/Projects/Flask/microblog/app/models.py", line 89, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "/home/aman/Projects/Flask/microblog/app/search.py", line 19, in query_index
    search = current_app.elasticsearch.search(
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/elasticsearch/client/__init__.py", line 810, in search
    return self.transport.perform_request(
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/elasticsearch/transport.py", line 351, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 257, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/elasticsearch/connection/base.py", line 181, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index [post]', post, index_or_alias)
2020-01-15 11:48:27,746 INFO: Microblog startup [in /home/aman/Projects/Flask/microblog/app/__init__.py:75]
2020-01-15 11:48:44,736 INFO: Microblog startup [in /home/aman/Projects/Flask/microblog/app/__init__.py:75]
2020-01-15 11:48:53,283 ERROR: Exception on /search [GET] [in /home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/flask/app.py:1890]
Traceback (most recent call last):
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/aman/Projects/Flask/microblog/app/main/routes.py", line 144, in search
    posts, total = Post.search(g.search_form.q.data, page,
  File "/home/aman/Projects/Flask/microblog/app/models.py", line 89, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "/home/aman/Projects/Flask/microblog/app/search.py", line 19, in query_index
    search = current_app.elasticsearch.search(
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/elasticsearch/client/__init__.py", line 810, in search
    return self.transport.perform_request(
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/elasticsearch/transport.py", line 351, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 257, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/elasticsearch/connection/base.py", line 181, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index [post]', post, index_or_alias)
2020-01-15 11:49:59,779 INFO: Microblog startup [in /home/aman/Projects/Flask/microblog/app/__init__.py:75]
2020-01-15 11:51:45,434 INFO: Microblog startup [in /home/aman/Projects/Flask/microblog/app/__init__.py:75]
2020-01-15 14:10:44,883 INFO: Microblog startup [in /home/aman/Projects/Flask/microblog/app/__init__.py:75]
